apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-fvjhdqlq
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/tsscui/go-fvjhdqlq:azure-b142a9da5d10aa89f49fe37dfe9f91ed423efec2
        name: container-image  
